version: "3"

services:
  tmsftt-db:
    image: mysql
    container_name: tmsftt-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TMSFTT
  tmsftt-apis:
    container_name: tmsftt-apis
    build: rest-api
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "30", "--", "./entrypoint.sh"]
    ports:
      - "9080:80"
    depends_on:
      - tmsftt-db
  tmsftt-web-server:
    container_name: tmsftt-web-server
    build: web-server
    ports:
      - "8080:80"
