version: "3.6"

services:
  tmsftt-db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MYSQL_DATABASE=TMSFTT
      - TZ=Asia/Shanghai
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "8078:3306"
    secrets:
      - mysql-root-password
  tmsftt-apis:
    image: sielab303/tmsftt-rest-apis:latest
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "120", "--", "uwsgi", "--ini", "/uwsgi.ini"]
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
      - TZ=Asia/Shanghai
    secrets:
      - django-secret-key
      - mysql-root-password
    depends_on:
      - tmsftt-db
    volumes:
      - media-data:/protected-files
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 3s
  tmsftt-web-server:
    image: sielab303/tmsftt-web-server:latest
    depends_on:
      - tmsftt-apis
    environment:
      - TZ=Asia/Shanghai
      - VIRTUAL_HOST=test.feingst.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.feingst.com
    volumes:
      - media-data:/protected-files:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  redis:
    image: redis:5.0.5-alpine
  celery-worker:
    image: sielab303/tmsftt-rest-apis
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "120", "--", "celery", "-A", "TMSFTT", "worker", "-l", "info"]
    depends_on:
      - redis
      - tmsftt-db
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
    secrets:
      - django-secret-key
      - mysql-root-password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  celery-beat:
    image: sielab303/tmsftt-rest-apis:latest
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "60", "--", "celery", "-A", "TMSFTT", "beat", "-l", "info"]
    depends_on:
      - redis
      - tmsftt-db
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
    secrets:
      - django-secret-key
      - mysql-root-password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  tmsftt-backup-full-daily:
    image: sielab303/tmsftt-full-backup:latest
    depends_on:
      - tmsftt-db
    volumes:
      - daily-full-backups:/backup
      - media-data:/media:ro
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=7
      - CRON_TIME=30 0 * * *
      - TIMEOUT=60s
      - BACKUP_MEDIA=0
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  tmsftt-backup-full-weekly:
    image: sielab303/tmsftt-full-backup:latest
    depends_on:
      - tmsftt-db
    volumes:
      - weekly-full-backups:/backup
      - media-data:/media:ro
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=4
      - CRON_TIME=30 0 * * 1
      - TIMEOUT=60s
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  tmsftt-backup-full-monthly:
    image: sielab303/tmsftt-full-backup:latest
    depends_on:
      - tmsftt-db
    volumes:
      - monthly-full-backups:/backup
      - media-data:/media:ro
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=24
      - CRON_TIME=30 0 1 * *
      - TIMEOUT=60s
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  tmsftt-backup-incremental:
    image: sielab303/tmsftt-incremental-backup:latest
    volumes:
      - incremental-backups:/backup
      - media-data:/media:ro
    environment:
      - CRON_TIME=30 0 * * *
      - TZ=Asia/Shanghai
      - BACKUP_FROM=/media
      - BACKUP_TO=/backup
  tmsftt-proxy:
    image: jwilder/nginx-proxy
    ports:
      - target: 80
        published: 80 #for redirect to HTTPS
        protocol: tcp
        mode: host #to bypass ingress mesh, to preserve client ip
      - target: 443
        published: 443
        protocol: tcp
        mode: host  #to bypass ingress mesh, to preserve client ip
    volumes:
      - conf:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./secrets/nginx-certs:/etc/nginx/certs
      - ./configs/nginx/real_ip.conf:/etc/nginx/conf.d/real_ip.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=test.feingst.com
    depends_on:
      - tmsftt-web-server
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - conf:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./secrets/nginx-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - tmsftt-proxy

secrets:
  django-secret-key:
    file: ./secrets/django-secret-key
  mysql-root-password:
    file: ./secrets/mysql-root-password

volumes:
  conf:
  html:
  vhostd:
  db-data:
  media-data:
  daily-full-backups:
  weekly-full-backups:
  monthly-full-backups:
  incremental-backups:

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.1.0/24