version: "3.6"

services:
  tmsftt-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MYSQL_DATABASE=TMSFTT
      - TZ=Asia/Shanghai
    volumes:
      - "./data/db-data:/var/lib/mysql"
    ports:
      - "8078:3306"
    secrets:
      - mysql-root-password
  tmsftt-apis:
    image: rest-apis:latest
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "120", "--", "uwsgi", "--ini", "/uwsgi.ini"]
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
      - TZ=Asia/Shanghai
    secrets:
      - django-secret-key
      - mysql-root-password
    depends_on:
      - tmsftt-db
    volumes:
      - "./data/media-data:/media"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 3s
  tmsftt-web-server:
    image: web-server:latest
    ports:
      - "8000:80"
    depends_on:
      - tmsftt-apis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./data/media-data:/media:ro"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  redis:
    image: redis:alpine
  celery-worker:
    image: rest-apis:latest
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "120", "--", "celery", "-A", "TMSFTT", "worker", "-l", "info"]
    depends_on:
      - redis
      - tmsftt-db
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
    secrets:
      - django-secret-key
      - mysql-root-password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  celery-beat:
    image: rest-apis:latest
    command: ["./wait-for-it.sh", "tmsftt-db:3306", "-s", "-t", "60", "--", "celery", "-A", "TMSFTT", "beat", "-l", "info"]
    depends_on:
      - redis
      - tmsftt-db
    environment:
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/mysql-root-password
      - DJANGO_SETTINGS_MODULE=TMSFTT.settings_prod
    secrets:
      - django-secret-key
      - mysql-root-password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
  tmsftt-backup-full-daily:
    image: full-backup
    depends_on:
      - tmsftt-db
    volumes:
      - "./data/backup/full/daily:/backup"
      - "./data/media-data:/media:ro"
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * *
      - TIMEOUT=60s
      - BACKUP_MEDIA=0
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  tmsftt-backup-full-weekly:
    image: full-backup
    depends_on:
      - tmsftt-db
    volumes:
      - "./data/backup/full/weekly:/backup"
      - "./data/media-data:/media:ro"
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=4
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * 1
      - TIMEOUT=60s
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  tmsftt-backup-full-monthly:
    image: full-backup
    depends_on:
      - tmsftt-db
    volumes:
      - "./data/backup/full/monthly:/backup"
      - "./data/media-data:/media:ro"
    environment:
      - MYSQL_HOST=tmsftt-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MAX_BACKUPS=24
      - INIT_BACKUP=1
      - CRON_TIME=0 0 1 * *
      - TIMEOUT=60s
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    secrets:
      - mysql-root-password
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  django-secret-key:
    file: ./secrets/django-secret-key
  mysql-root-password:
    file: ./secrets/mysql-root-password